export default {
    LOGO: require("../assets/images/logo.png"),
    WELCOME: require("../assets/images/welcome.png"),
    DISCOVER: require("../assets/images/discover.png"),
    DELIVER: require("../assets/images/deliver.png"),
    FAVORITE: require("../assets/images/favorite.png"),
    FACEBOOK: require("../assets/images/facebook.png"),
    GOOGLE: require("../assets/images/google.png"),
    LOADING: require("../assets/images/loading.json"),
    FRIED_CHICKEN: require('../assets/images/fried_chicken.png'),
    BURGER: require('../assets/images/burger.png'),
    PIZZA: require('../assets/images/pizza.png'),
    DESSERT: require('../assets/images/dessert.png'),
    NOODLES: require('../assets/images/noodles.png'),
    DRINKS: require('../assets/images/drinks.png'),
    DELIVERY_TIME: require('../assets/images/delivery_time.png'),
    DELIVERY_CHARGE: require('../assets/images/delivery_charge.png'),
    MARKER: require('../assets/images/marker.png'),
    EMPTY_CART: require('../assets/images/empty_cart.png'),
    FEMALE_AVATAR: require('../assets/images/female_avt.png'),
    MALE_AVATAR: require('../assets/images/male_avt.png'),
    DEFAULT_AVATAR: require('../assets/images/default_avt.png'),
    EMPTY_SEARCH: require("../assets/images/emptySearch.png")
};
